### ISSUE TITLE
Issue with google home

### ISSUE THREAD

**Issue by xtego** [gjunky/hubitat-ModernForms#1]
First of all, thank you for your work on this.  I have this code installed and working with two fans.  In fact, I made the decision to buy these fans based on the fact that this code existed, so thank you!  

Here's where I'm having trouble:  All control within hubitat works great.  However, when I try to add these devices to the Google Home App or Assistant, I get this error in the Hubitat Logs: "The following devices are not supported by Google Home and will be removed from your device list:[Loft Fan]"

I've been trying to narrow down the issue on my own, but I'm a bit over my head.  At first I thought it was the capabilities being presented by the driver, but I tried messing with different variations and still can't get it to be recognized.  

I also tried to break the fan and light features apart into two separate drivers.  However, this also still fails in google home. 

I'm wondering if this is something you have the ability to test and troubleshoot?

**Comment by gjunky** [comment]
Hubitat/Google Don't support fans right now. If you look at your devices in the Google app in Hubitat, you will see that the ceiling fan devices are removed from the list of synced devices. I hear that selecting it as switch or dinner device might work but I have not tried it.
